In [53]:
import os
import glob
import numpy as np
import pandas as pd

xyz_files = os.path.join(os.path.dirname(os.getcwd()), 'data', "*.xyz")
data_dir = os.path.join(os.path.dirname(os.getcwd()), 'data')

In [37]:
df = None
for xyz_file in xyz_files: df = pd.read_table(xyz_file, skiprows=2, delim_whitespace=True,names=['EASTING', 'NORTHING', xyz_file.split("\\")[-1][:-4]])
df

,EASTING,NORTHING,SA_TMI_RTP,SA_RESIDUAL,LOG_SA_GRAV_Slope,SA_GRAV,LOG_GCAS_RTP_2VD,LOG_Distance_to_Faults,Log_Distance_to_Archaean_Contact
0,113491.373,6.974338e+06,-99999.0,-99999.0,-3.402823e+38,-99999.0,-3.402823e+38,-99999.0,-99999.0
1,113741.373,6.974338e+06,-99999.0,-99999.0,-3.402823e+38,-99999.0,-3.402823e+38,-99999.0,-99999.0
2,113991.373,6.974338e+06,-99999.0,-99999.0,-3.402823e+38,-99999.0,-3.402823e+38,-99999.0,-99999.0
3,114241.373,6.974338e+06,-99999.0,-99999.0,-3.402823e+38,-99999.0,-3.402823e+38,-99999.0,-99999.0
4,114491.373,6.974338e+06,-99999.0,-99999.0,-3.402823e+38,-99999.0,-3.402823e+38,-99999.0,-99999.0
...,...,...,...,...,...,...,...,...,...
6391565,788241.373,6.384088e+06,-99999.0,-99999.0,-3.402823e+38,-99999.0,-3.402823e+38,-99999.0,-99999.0
6391566,788491.373,6.384088e+06,-99999.0,-99999.0,-3.402823e+38,-99999.0,-3.402823e+38,-99999.0,-99999.0
6391567,788741.373,6.384088e+06,-99999.0,-99999.0,-3.402823e+38,-99999.0,-3.402823e+38,-99999.0,-99999.0
6391568,788991.373,6.384088e+06,-99999.0,-99999.0,-3.402823e+38,-99999.0,-3.402823e+38,-99999.0,-99999.0
6391569,789241.373,6.384088e+06,-99999.0,-99999.0,-3.402823e+38,-99999.0,-3.402823e+38,-99999.0,-99999.0

In [62]:
mineralogy = pd.read_csv(os.path.join(xyz_dir, "Mineralogy.csv"))
points = list(zip(list(mineralogy["NORTHING_GDA2020"], mineralogy["EASTING_GDA2020"])))
for pt in points: index = df.loc[(df['EASTING']-pt[0]>=0) & (df['EASTING']-pt[0]<250) & (pt[1]-df['NORTHING']>=0) & (pt[1]-df['NORTHING']<250)].index.tolist()
df.to_csv(os.path.join(data_dir, "GawlerTensor.csv"), index=False)
df.loc[df['Mineralogy'] == 1]

,EASTING,NORTHING,SA_TMI_RTP,SA_RESIDUAL,LOG_SA_GRAV_Slope,SA_GRAV,LOG_GCAS_RTP_2VD,LOG_Distance_to_Faults,Log_Distance_to_Archaean_Contact,Mineralogy
14648,392991.373,6.973088e+06,-99999.000000,-99999.000000,-3.402823e+38,-99999.000000,-3.402823e+38,-99999.000000,-99999.000000,1
133484,335991.373,6.962088e+06,-99999.000000,-99999.000000,-3.402823e+38,-99999.000000,-3.402823e+38,-99999.000000,-99999.000000,1
142934,668991.373,6.961338e+06,-99999.000000,-99999.000000,-3.402823e+38,-99999.000000,-3.402823e+38,-99999.000000,-99999.000000,1
174875,536241.373,6.958338e+06,-99999.000000,-99999.000000,-3.402823e+38,-99999.000000,-3.402823e+38,-99999.000000,-99999.000000,1
180523,595241.373,6.957838e+06,-105.414078,0.555792,-1.535274e+00,-19.287619,-1.663873e+00,10.583199,8.944396,1
...,...,...,...,...,...,...,...,...,...,...
6382735,610241.373,6.384838e+06,-99999.000000,-99999.000000,-3.402823e+38,-99999.000000,-1.090703e+00,-99999.000000,-99999.000000,1
6384381,345241.373,6.384588e+06,-99999.000000,-99999.000000,-3.402823e+38,-99999.000000,-3.402823e+38,-99999.000000,-99999.000000,1
6384737,434241.373,6.384588e+06,-99999.000000,-99999.000000,-3.402823e+38,-99999.000000,-3.402823e+38,-99999.000000,-99999.000000,1
6385398,599491.373,6.384588e+06,-99999.000000,-99999.000000,-3.402823e+38,-99999.000000,2.728245e-01,-99999.000000,-99999.000000,1
6388330,655991.373,6.384338e+06,-99999.000000,-99999.000000,-3.402823e+38,-99999.000000,2.423389e+00,-99999.000000,-99999.000000,1